apiVersion: v1
kind: Service
metadata:
  name: object-mocker
  namespace: mockers
  labels:
    app: object-mocker
    version: v1beta
spec:
  ports:
    - port: 3000
      name: http-prom-port
  selector:
    app: object-mocker
    version: v1beta
---
apiVersion: v1
kind: Service
metadata:
  name: object-mocker-np
  namespace: mockers
  labels:
    app: object-mocker
    version: v1beta
spec:
  ports:
    - port: 3000
      name: http-prom-port
  selector:
    app: object-mocker
    version: v1beta
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-mocker
  namespace: mockers
  labels:
    app: object-mocker
    version: v1beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-mocker
      version: v1beta
  template:
    metadata:
      namespace: mockers
      labels:
        app: object-mocker
        version: v1beta
    spec:
      containers:
        - name: object-mocker
          image: mxudong/object-mocker:v1.0.0
          ports:
            - containerPort: 3000
              name: http-server